### ISSUE TITLE
Global pre-commit exclude does not work for dead

### ISSUE THREAD

**Issue by feluelle** [asottile/dead#87]
The global option `exclude` does not work for the `dead` hook.
```
exclude: "..."
repos:
  - repo: ...
```

To workaround this I exclude for this hook additionally:
```
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead
        args: ["--exclude", "..."]
```
