### ISSUE TITLE
Add a better interface for only checking specific files in a larger codebase

### ISSUE THREAD

**Issue by sirosen** [asottile/dead#90]
As always, thanks for the tools! ❤️ 

I use `dead` on a small number of files in a larger codebase, and have it integrated via `pre-commit`. We're only using `dead` where we consider it particularly helpful.

Right now, this means that we have a config in pre-commit like so:
```yaml
- repo: https://github.com/asottile/dead
  rev: v1.4.0
  hooks:
    - id: dead
      args:
        - "--files"
        - |
          (?x)(
            src/project/component1/foo.py|
            src/project/component1/bar/baz.py|
            src/project/component2/spam.py
          )
```

This feels awkward as the list grows. Plus, it reports things inaccurately if they're used in a module which I don't want covered by `dead`.

I'm trying to work out the right approach. It would be really cool to have `dead` read the full codebase as it does by default, but only report failures in the target files.
e.g.
```yaml
      args:
       # `--check-files` or `--report-files` or `--only` or some other name is fine
        - "--report-files"
        - "src/project/component1/foo.py"
        - "src/project/component1/bar/baz.py"
        - "src/project/component2/spam.py"
```

I'm more than happy to try to contribute a patch if this would be acceptable. I don't want to bloat things. I think just a filter at the very end,  when output and the exit code are being handled, to see if the passed `--report-files` matches files before treating them as failures.

Does this sound interesting as a feature?
